#                   _   _ _    _            _ _   _     _____           _ _           _
#       /\         | | (_) |  | |          | | | | |   |_   _|         | (_)         | |
#      /  \   _ __ | |_ _| |__| | ___  __ _| | |_| |__   | |  _ __   __| |_  ___ __ _| |_ ___  _ __
#     / /\ \ | '_ \| __| |  __  |/ _ \/ _` | | __| '_ \  | | | '_ \ / _` | |/ __/ _` | __/ _ \| '__|
#    / ____ \| | | | |_| | |  | |  __/ (_| | | |_| | | |_| |_| | | | (_| | | (_| (_| | || (_) | |
#   /_/    \_\_| |_|\__|_|_|  |_|\___|\__,_|_|\__|_| |_|_____|_| |_|\__,_|_|\___\__,_|\__\___/|_|
#

debug:
  # If enabled, the plugin will print debug messages to players with the permission "AntiHealthIndicator.Debug".
  enabled: false

# This option determines whether the plugin will check for an update on startup.
update-checker:
  enabled: true

  # When an update is found, should it be printed to the console?
  print-to-console: true

  # When an update is found, should players with the permission "AntiHealthIndicator.Notify" be notified?
  notify-in-game: true

# These options determine what information should be spoofed.
spoof:
  # Prevents the player from receiving the current saturation of their food bar,
  # which can be used by mods or cheats to determine when the food bar itself will be drained.
  food-saturation:
    enabled: false

  # If enabled, the gamemode of the player will be spoofed to other players.
  # This means that other players will not see the actual gamemode of the player.
  # For example, if a player is in creative mode, other players will see the player in survival mode.
  # Note: Players in spectator will not be spoofed to prevent issues.
  gamemode:
    enabled: true

  # Prevents the health of team members from being sent to the players due to being on the same team.
  # Some bad plugins use minecraft teams to color names, etc. and this can be used to determine health.
  # If this causes issues with other plugins that use teams, you can disable this.
  team-scoreboard:
    enabled: true

  # These options determine what entity data should be spoofed.
  entity-data:
    # If disabled, none of the following settings will have any effect.
    enabled: true

    # If enabled, metadata (like health, absorption, etc.) will only be hidden for other players.
    # Entities other than players are ignored (like mobs, animals, etc.).
    # When enabled, the ignored vehicles, wolves and iron golems settings will have no effect.
    players-only:
      enabled: false

    # Prevents a player from receiving max health and max absorption attributes from other players.
    attributes:
      enabled: true

    # If enabled, hides the oxygen number of other entities.
    air-ticks:
      enabled: true

    # If enabled, masks the health of other entities. Other players cannot see these entities' health.
    health:
      enabled: true

    # If enabled, hides the absorption of other players.
    absorption:
      enabled: true

    # if enabled, hides the amount of experience of other players.
    xp:
      enabled: true

    # If enabled, hides certain information about other players their held or wearing items.
    items:
      enabled: true

      # If enabled, hides the number of items in a stack the player is holding.
      # For example, if a player holds a block, it won't show the number of blocks in the stack
      stack-amount:
        enabled: true

      # If enabled, hides the durability of other players items (e.g., tools, armor).
      durability:
        enabled: true

        # If enabled, elytra durability spoofing will be disabled when the elytra's durability is 1 or less.
        broken-elytra:
          enabled: true

      # If enabled, hides the enchantments of other players items (e.g., tools, armor).
      # For example, if a player holds a sword with sharpness 5, it won't show the sharpness enchantment.
      # But rather Luck of the Sea I, which is not true, but we need to apply at least one enchantment
      # client-side, otherwise the client will render the item as if not enchanted.
      enchantments:
        enabled: true
